:: type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_IP1.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\explore.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\MIP\\IP1\\x64\\Debug\\IP1.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\T1\\T1_medium\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_IP1.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_IP2.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\explore.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\MIP\\IP2\\x64\\Debug\\IP2.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\T1\\T1_medium\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_IP2.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_600_1_NT_MIPStart_QCH_IP3.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\MIP\\IP3\\x64\\Release\\IP3.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\todo\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_600_1_NT_MIPStart_QCH_IP3.txt
type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_0606_T14_180_1_1_noCPStart.txt
perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\CP\\jobBased\\x64\\Release\\jobBased.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\T14 C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_0606_T14_180_1_1_noCPStart.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_LH.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\explore.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\Heuristics\\LH\\x64\\Debug\\LH.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\T1\\T1_medium\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_T1_medium_2301_LH.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_1_SCH.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\Heuristics\\SCH\\x64\\Release\\SCH.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_1_SCH.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_NT_QCH.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\Heuristics\\QCH\\x64\\Release\\QCH.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_NT_QCH.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_NT_RHQCH.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\Heuristics\\RH\\x64\\Release\\RH.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_1_NT_RHQCH.txt
::type nul > C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_600_1_NT_SAQCH.txt
::perl -w C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\exploreSet1.pl C:\\users\\margaux.nattaf\\Documents\\Visual_Studio_2013\\Projects\\Heuristics\\SA\\x64\\Release\\SA.exe C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\instances\\Ali_scheme\\set1\\ C:\\users\\margaux.nattaf\\Documents\\Dev_dos\\PTC\\resultat\\res_2601_set1_600_1_NT_SAQCH.txt